Calculate the size of a signature by doing a trial run. The size of 287 is valid only for 2048-bit RSA keys. For 4096-bit RSA keys, for DSA keys it is different.
E.g. trying to use a 4096-bit RSA key failed:
java.lang.RuntimeException: Error writing pending entry '268'.
  at org.redline_rpm.header.AbstractHeader.writePending(AbstractHeader.java:213)
  at org.redline_rpm.Builder.build(Builder.java:1391)
  ...
Caused by: java.nio.BufferOverflowException
  at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)
  at java.nio.ByteBuffer.put(ByteBuffer.java:859)
  at org.redline_rpm.header.AbstractHeader$BinEntry.write(AbstractHeader.java:684)
  at org.redline_rpm.header.AbstractHeader.writePending(AbstractHeader.java:208)